### ISSUE TITLE
PHP 7.3/7.4 Notice warning

### ISSUE THREAD

**Issue by hyfox** [AdamB7586/pdo-dbal#13]
Hey,

Super cool package - I've enjoyed using it. After upgrading PHP to 7.4 (skipping 7.3) most of my requests now gives the following warning:
> Notice: Trying to access array offset on value of type int in /usr/www/users/webinstance/cmp/vendor/adamb/database/src/Database.php on line 560

It does not seem that functionality is affected.

Best,
Albert

**Comment by AdamB7586** [comment]
I have just updated the code to fix this warning, It only appears to affect PHP 7.4
