### ISSUE TITLE
values is persistent sometimes

### ISSUE THREAD

**Issue by zbee** [AdamB7586/pdo-dbal#14]
I am trying to write a project using pdo-dbal, however when I make more than one query in a call using the MemcacheCache wrapper I am getting persistence in the `values` class variable.

See below. The first entry is the first query on the page, the second query is the next. The second query still contains the first query's `values` despite not being passed in. The second image shows the second query's dbal call.

![image](https://user-images.githubusercontent.com/1582821/78859627-26991c80-79ed-11ea-9cb9-eed5610ee470.png)

![image](https://user-images.githubusercontent.com/1582821/78859689-547e6100-79ed-11ea-80ef-e9371ec105bb.png)

I tried changing the first call's synonymous column of `id` to `lobbyID` thinking it was being cached that way, but this did not fix anything.

I can fix this by making `values` public, and setting it to `[]` just like what `\DBAL\Database\executeQuery()` tries to do, but somehow fails in doing so; I can also fix it by clearing `values` as the first action in `\DBAL\Database\select()`, see below.

![image](https://user-images.githubusercontent.com/1582821/78859935-12a1ea80-79ee-11ea-8931-10d6095d603a.png)

I tried removing the `unset()` calls, and I tried moving `values = []` to right after the bind, but neither of those solved the issue, only clearing `values` from outside the class.

If I could get xdebug working I could try to narrow it down further, but I guess that isn't happening.

**Comment by AdamB7586** [comment]
I have just released a new version that should resolve this issue
