### ISSUE TITLE
Documentation for Select

### ISSUE THREAD

**Issue by RBuryak** [AdamB7586/pdo-dbal#15]
Can you provide documentation for the following implementation:

1. SELECT * FROM table_name WHERE field_name1 = value1 AND/OR ( field_name2 = value2 AND/OR field_name3 = value3).
2. JOIN using in SELECT

Thank you in advance!

**Comment by AdamB7586** [comment]
I have added some additional examples to the query method as both of these queries would have to be handle using the $db->query() method rather than the $db->select()
