### ISSUE TITLE
Documentation for IN() statements

### ISSUE THREAD

**Issue by spyke01** [AdamB7586/pdo-dbal#8]
Can you provide documentation for the following implementation:

`
SELECT * FROM table_name WHERE field_name IN (values)
`

I tried using the following but its not working:

`
$dbInstance->selectAll( 'table_name', [ 'field_name ' => [ 'IN' => [ 'value1', 'value2' ] ] ] );
`

The returned SQL is:

`SELECT * FROM `table_name` WHERE `field_name ` %s ?;`

Which is using the format from the IN operator but not really what I'm looking for.

Should I be using a different call or $where array structure?

**Comment by AdamB7586** [comment]
I've just released an update to fix this issue, it should now work using the same call you used.

It looks like I had forgotten about finishing the usage of the IN operator in SQL statements.
